// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWAclw-NEQ4L-TB-2SW9LXfo2l8YE9Ms',
    appId: '1:996656980247:web:ef29d5dfbc23e290645752',
    messagingSenderId: '996656980247',
    projectId: 'quicksurveys-8d75a',
    authDomain: 'quicksurveys-8d75a.firebaseapp.com',
    storageBucket: 'quicksurveys-8d75a.firebasestorage.app',
    measurementId: 'G-YRLDP46NXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6WFXbal3YViLU5EF2pefTLZhAl61dOZs',
    appId: '1:996656980247:android:2686fc9673969cc9645752',
    messagingSenderId: '996656980247',
    projectId: 'quicksurveys-8d75a',
    storageBucket: 'quicksurveys-8d75a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzYe7LuXmst0sbN09n9kmVOv1D_5pj3ZY',
    appId: '1:996656980247:ios:c87aafabedffd560645752',
    messagingSenderId: '996656980247',
    projectId: 'quicksurveys-8d75a',
    storageBucket: 'quicksurveys-8d75a.firebasestorage.app',
    androidClientId: '996656980247-765khj22oh4t0n6evtvaf15258vavlqg.apps.googleusercontent.com',
    iosClientId: '996656980247-h8902ott1q7hbshop5oi60fvoc1ha0g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveys',
  );
}
