// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgkLX85hjyl3zLlYKh4QMLs_wg66oFsY',
    appId: '1:908967302608:web:c80d3668da6e58590b15d5',
    messagingSenderId: '908967302608',
    projectId: 'quicksurveys',
    authDomain: 'quicksurveys.firebaseapp.com',
    storageBucket: 'quicksurveys.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNM2Fe80SFmob9h2qT9nfsS_wkH3yEk3w',
    appId: '1:908967302608:android:3247ec5dbe5b1d6e0b15d5',
    messagingSenderId: '908967302608',
    projectId: 'quicksurveys',
    storageBucket: 'quicksurveys.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpYmEhddKpGJ0UUw7kBc5dWzTa9dSKUfE',
    appId: '1:908967302608:ios:9b3861cf2c94d7fa0b15d5',
    messagingSenderId: '908967302608',
    projectId: 'quicksurveys',
    storageBucket: 'quicksurveys.firebasestorage.app',
    androidClientId: '908967302608-5r3e9dqp1e54e52i8s3meiokbdcn77c0.apps.googleusercontent.com',
    iosClientId: '908967302608-om49obrea5qhq2r6f9dljuei04nh6qrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveys',
  );
}
